name: dnd_dice_roller
description: A dice rolling application
version: 1.0.0
# repository: https://github.com/themichaelfink/dnd-dice-roller

environment:
  sdk: ^3.3.1

dependencies:
  web: ^0.4.0

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  lints: ^3.0.0
